### ISSUE TITLE
Dynamic submenus and/or Destroy PopMenu

### ISSUE THREAD

**Issue by nicollasricas** [fujaru/popmenu#1]
Hi,

Is there a way to create dynamic submenus or destroy the popmenu then I could rebuild entirely?

Nice plugin.

Have a nice day
Thanks

**Comment by fujaru** [comment]
Hi,

Thanks for using PopMenu plugin!

To create dynamic submenu you could first create a PopMenu instance and assign it to 'submenu' option on a PopMenuItem. For example:

```
$(elm).popmenu({
    item1: {label: 'New'},
    item2: {label: 'Open'}
});

var newSubmenu = new PopMenu({
    newFile: {label: 'Blank File'},
    newPng: {label: 'Image File (png)'},
    newDoc: {label: 'Text Document (doc)'},
    newXls: {label: 'Spreadsheet (xls)'}
});
$(elm).popmenu().find('item1').options({ submenu: newSubmenu });
```

Currently there is no method to destroy or reassign an element to different popmenu. I will open a separate ticket to track this.

Hope it helps. Have a nice day!
Fajar

**Comment by nicollasricas** [comment]
Sorry for late reply!

That helps, thanks!
