### ISSUE TITLE
Use a instance of popmenu with multiple triggers

### ISSUE THREAD

**Issue by Trxplz0** [fujaru/popmenu#3]
I was trying use the same popmenu instance with two triggers (buttons) but doesn't work.

My menu is built-in dynamic using some data from ajax.

Is this possible? It would be nice if were....

Thanks

**Comment by Trxplz0** [comment]
Found on docs!

**Comment by fujaru** [comment]
Hi Trxplz0,
Glad to know you solved it already.
Thanks for using PopMenu plugin!
